max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
edition = "2021"
imports_granularity = "Module"
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Default"
comment_width = 80

fn_params_layout = "Tall"
fn_call_width = 100
array_width = 60
attr_fn_like_width = 80
chain_width = 100
